//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Library.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LIBRARY_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ADMINLOG             129
#define IDD_DIALOG_REGISTER             131
#define IDB_BITMAP1                     132
#define IDB_BITMAP2                     133
#define IDB_BITMAP3                     134
#define IDB_BITMAP4                     135
#define IDB_BITMAP_ABOUT                136
#define IDB_BITMAP5                     137
#define IDB_BITMAP_TITLE                138
#define IDB_BITMAP_BLANK2               139
#define IDB_BITMAP6                     140
#define IDB_BITMAP_ADMIN                141
#define IDB_BITMAP_MANAGER              142
#define IDB_BITMAP_BOOK1                143
#define IDB_BITMAP_BOOK2                144
#define IDB_BITMAP_BOOK3                145
#define IDB_BITMAP_BOOK4                146
#define IDB_BITMAP_BOOK5                147
#define IDB_BITMAP_BOOK6                148
#define IDB_BITMAP_BOOK7                149
#define IDB_BITMAP_BACKGROUNDLEFT       150
#define IDB_BITMAP_BACKGROUNDTOPLEFT    151
#define IDB_BITMAP_BACKGROUNDCENTER     152
#define IDB_BITMAP_BACKGROUNDTOPRIGHT   153
#define IDB_BITMAP_BACKGROUNDBELOW      154
#define IDB_BITMAP_BACKGROUNDRIGHT      155
#define IDD_DIALOG_USER                 156
#define IDD_DIALOGPERSONALINFO          158
#define IDD_DIALOGADMIN                 159
#define IDD_DIALOG_ADMIN                159
#define IDD_DIALOG_USERINFORMATION      163
#define IDD_DIALOG_SE                   164
#define IDD_DIALOG_MANAGEBOOK           164
#define IDD_DIALOG_SEARCH               165
#define IDD_DIALOG_CREATEADMIN          166
#define IDD_DIALOG_READERINFOMANAGE     167
#define IDB_BITMAP7                     172
#define IDB_BITMAP8                     173
#define IDB_BITMAP9                     177
#define IDB_BITMAP10                    178
#define IDD_INSERTBOOK                  179
#define IDD_DIALOG_RECOMMEND            180
#define IDC_STATIC_READER               1000
#define IDC_EDIT_READER                 1002
#define IDC_EDIT_READERCODE             1003
#define IDC_BUTTON_LOG                  1004
#define IDC_BUTTON_REGISTER             1005
#define IDC_BUTTON_ABOUT                1006
#define IDC_BUTTON_ADMINLOG             1007
#define IDC_EDIT_ADMINNAME              1009
#define IDC_EDIT_ADMINCODE              1010
#define IDC_EDIT_REGISTERNAME           1011
#define IDC_EDIT_MAIL                   1012
#define IDC_EDIT_REGISTERCODE           1013
#define IDC_EDIT_REGISTERCODE_CONFIRM   1014
#define IDC_BUTTON_OKTODETAIL           1015
#define IDC_EDIT_REGISTERINTEREST       1017
#define IDC_EDIT_REGISTERMAJOR          1019
#define IDC_BUTTON_REGISTER_CANCEL      1022
#define IDC_BUTTON_LOG_HELP             1023
#define IDC_BUTTONSEARCH                1027
#define IDC_BUTTONSEARCH2               1028
#define IDC_LIST1                       1033
#define IDC_BUTTONRESERVE               1034
#define IDC_BUTTONPERSONALINFOMANAGE    1039
#define IDC_BUTTON_CHANGEPASSWORD       1039
#define IDC_BUTTON_CREATEADMIN          1040
#define IDC_BUTTON_USERINFO             1041
#define IDC_BUTTON_ADD                  1048
#define IDC_BUTTON1                     1055
#define IDC_BUTTON_BOOKMANAGE           1055
#define IDC_BUTTON_GO                   1055
#define IDC_BUTTON_SEARCH               1055
#define IDC_EDIT_SEARCH                 1056
#define IDC_BUTTON_EDIT                 1058
#define IDC_BUTTON4                     1059
#define IDC_BUTTON_ALL                  1059
#define IDC_BUTTON_DELETE               1060
#define IDC_LIST2                       1061
#define IDC_BUTTON6                     1062
#define IDC_BUTTON_QUIT                 1063
#define IDC_EDIT_TITLE                  1064
#define IDC_EDIT_AUTHOR                 1065
#define IDC_EDIT_YEAR                   1066
#define IDC_EDIT_CLASSIFACATION         1067
#define IDC_EDIT_AV                     1068
#define IDC_BUTTON_SAVE                 1069
#define IDC_EDIT_PASSWORD               1070
#define IDC_EDIT_USERNAME               1071
#define IDC_EDIT_INTEREST               1072
#define IDC_EDIT_MAJOR                  1073
#define IDC_EDIT_NAME                   1075
#define IDC_EDIT_CONFIRM                1077
#define IDC_BUTTON_DESTROY              1078
#define IDC_EDIT_F                      1080
#define IDC_EDIT_E_MAIL                 1085
#define IDC_COMBO1                      1088
#define IDC_BUTTON_CLEAN                1089
#define IDC_EDIT1                       1091
#define IDC_EDIT2                       1092
#define IDC_EDIT3                       1093
#define IDC_EDIT4                       1094
#define IDC_EDIT5                       1095
#define IDC_BUTTON_RESERVE              1096
#define IDC_EDIT7                       1096
#define IDC_EDIT9                       1097
#define IDC_EDIT6                       1098
#define IDC_EDIT10                      1098
#define IDC_BUTTON2                     1099
#define IDC_EDIT_HIT                    1100
#define IDC_BUTTONDESTROY               1101
#define IDC_EDIT8                       1102
#define IDC_BUTTON                      1103
#define IDC_BUTTON_OUT                  1103
#define IDC_BUTTON3                     1104
#define IDC_BUTTON_RESER                1105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
